language: ruby
rvm:
  - 2.6.3

before_script:
 - chmod +x ./script/cibuild # or do this locally and commit

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script: ./script/cibuild

# branch whitelist, only for GitHub Pages
branches:
  only:
  - master       # test the master branch
  - /pages-(.*)/ # test every branch which starts with "pages-"

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

addons:
  apt:
    packages:
    - libcurl4-openssl-dev
  browserstack:
    username:
      secure: "E7D5lgByyVE+BuJ58MXyoj/1FzdAngjCA4r/xASR8yKItyeJ7KAobVBDZLJ045mrtDxgzCji0s/GFZ+SFfANSmzNW+J3g83VYY19GWQfjSmtUe1hpjkKzfgZPV+BFBnq4rZG6n9BoJx23+AHJka+1vhSnRf1nvOeSpt2uypwt6cA3hopTN2/5rIPNrYhpR38UTe0/ITwa18Vw753zbk1L5Wp68axc+v885CXXLxqNPVZ3XM3EzKvis+rECabLSjbQybMg61/2f/5OTPP+rBaEZjw3B19rUMje3J+ucwuhKWiwmjEE6Q29PZM3Da6wowxPgtVCJ7umN/kktvXYDvMO/JVsz3O36eUU5HW+uyvg2t0o9t01P+FM3BO5sw2nRhJGFwawMZOVoX6i/4YN3XxTB8fYzFFSrA5CsJFyZ79GRxA/fC425XfjQPuB4/q14vXHLD6aHXL8or/FMzXBwRmDM9sR9O3a5sQmh6Adp9V/BQKWPFfHEsfnIXKWnxCZ46p459es8ihM4Ncq/dQDncXSuPph8Y1JzYJmQo5OqUAPmLvLy5WYhLqN+Q8OHrkZmcOywDh9IggH7XmGSUSeYsRWZwKvcSnyKuxJ8tu9JTpdwW9ZclQYIslp6bz6GaIqFHsqJK7hayQIX3z+AOB1snQOkPZ6gEy4O0vLbsPx+eUvug="
    access_key:
      secure: "MCnM2N7h4Z4bfpN9nJlrOQYCQFkbHlI+z7CG8ehD+uhC1ROs9CPW5AYlFfTwXF8uCZVNnovy2Yot87Po8S267/KiZrqble8X5+Xej4ne7WtprWeKpuY8e47uZO45JVLWRI+AiNRwPOhtvkQDsvN5PNGrVFkz1OUGewekj2bTr9PoQWTKz5jeWbr67kSTJBtBIP3grUq/iGesL8rHCRPSUTB5kLf9AFTvX1UgzKCv4J+RI8Ek2WTY+uq2ffOWq1O+bE4S4iDxZdkIKd0L6bYFYDKmswva5XQzmqud/o4TqW5j4OT85+W//rKIb2KmIC1sFVCITDE/q4z2AKGd9w65TQJut0fA98+0pSWDTHhmceu5l/CobWv28Q2S3Pp/S8nLsK6denrdwQlM1AZ7X5ozvDHhGjKKITRGia5/W+/FKsH2QhT1ftkpMwhnFbq/sXpJuYWPMSS65OFpXqVvVAQGPU9Gr4E0kg/xLzUre76lkbKT9H7f0BN8FWXNl5ZLsaGLlnzRwRsx9n6cI5HBT2+4VvIh69GIfao7emZ9pogqxszam3pN4b21w1XBf+Hs19uKFfaHLmZSz/DN/AbIIZx8bHeXW68EfDAyGqm8GNOnaGeT+oGcyilIg+rVFgU0jBD4MwushqaeZgp0pARBUcvMa5SLUe9FDFGdXLDfr5rMmew="

sudo: false # route your build to the container-based infrastructure for a faster build

cache: bundler # caching bundler gem packages will speed up build

# Optional: disable email notifications about the outcome of your builds
notifications:
  email: false
